title: "Carmen Pelayo Fernández"
description: "BBVA Research | AI, Economics, Geopolitics"
baseurl: ""
url: "https://carmenpelayo.github.io"

theme: minima

plugins:
  - jekyll-feed

email: carmen.pelayo@bbva.com
github_username: carmenpelayo
linkedin_username: carmenpelayofernandez
