title: "Carmen Pelayo"
description: "Data Scientist | AI, Economics, Policy"

baseurl: ""
url: "https://carmenpelayo.github.io"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

email: carmen.pelayo@bbva.com
github_username: carmenpelayo
linkedin_username: carmenpelayofernandez
